// Generated by https://quicktype.io

export interface Provincia {
    cantidad:   number;
    inicio:     number;
    provincias: ProvinciaElement[];
    total:      number;
}



export interface ProvinciaElement {
  
    id:        string;
    nombre:    string;
}

